openapi: 3.0.3
info:
  title: Title Document Creator API (Pro)
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /v1/parse-ascii:
    post:
      summary: Parse SPIN 2 ASCII to canonical XML
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                ascii_text:
                  type: string
                  example: "TH123456789012S20240201DOC000012345TFRSALBT00012345EDM0CITY OF EDMONTON\n"
      responses:
        '200':
          description: Parsed XML
          content:
            application/json:
              schema:
                type: object
                properties:
                  xml:
                    type: string
               examples:
                 sample:
                   summary: Canonical XML output
                   value:
                     xml: "<ProductTitleResult>\n  <Order>\n    <OrderNumber>123456</OrderNumber>\n  </Order>\n  <TitleData>\n    <Title>...</Title>\n  </TitleData>\n</ProductTitleResult>"
  /v1/validate:
    post:
      summary: Validate canonical XML against SPIN 2 XSD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [xml]
              properties:
                xml:
                  type: string
                  example: "<ProductTitleResult>...</ProductTitleResult>"
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message: { type: string }
                        line: { type: integer, nullable: true }
                        column: { type: integer, nullable: true }
               examples:
                 success:
                   summary: Valid document
                   value:
                     ok: true
                     errors: []
                 failure:
                   summary: Invalid document
                   value:
                     ok: false
                     errors:
                       - message: "Element 'TitleNumber': [facet 'maxLength']"
                         line: 4
                         column: 24
  /v1/ingest-pdf:
    post:
      summary: Ingest prior title PDF to produce XML candidates (backfill)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: XML candidates
          content:
            application/json:
              schema:
                type: object
                properties:
                  xml_candidates:
                    type: array
                    items:
                      type: string
                  confidence:
                    type: number
                    format: float
               examples:
                 extracted:
                   summary: Candidate derived from prior PDF
                   value:
                     xml_candidates:
                       - "<ProductTitleResult>...</ProductTitleResult>"
                     confidence: 0.72
  /v1/render:
    post:
      summary: Render canonical XML to pixel-perfect PDF
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [xml]
              properties:
                xml:
                  type: string
                template_id:
                  type: string
                  default: alberta_title_v1
                options:
                  type: object
                  properties:
                    pdfa:
                      type: boolean
                      default: true
             examples:
               default:
                 summary: Render sample XML
                 value:
                   xml: "<ProductTitleResult>...</ProductTitleResult>"
                   template_id: alberta_title_v1
                   options:
                     pdfa: true
      responses:
        '200':
          description: Rendered PDF
          content:
            application/pdf:
              schema:
                type: string
                format: binary
  /v1/reserve-title-number:
    post:
      summary: Reserve or generate a title number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                strategy:
                  type: string
                  enum: [sequential, uuid, external]
                  default: sequential
                seed:
                  type: string
      responses:
        '200':
          description: Reserved number
          content:
            application/json:
              schema:
                type: object
                properties:
                  title_number:
                    type: string
  /v1/templates:
    get:
      summary: List available templates
      responses:
        '200':
          description: Templates
          content:
            application/json:
              schema:
                type: object
                properties:
                  templates:
                    type: array
                    items:
                      type: object
                      properties:
                        template_id: { type: string }
                        version: { type: string }
                         page:
                           type: object
                         modified_at: { type: string }
               examples:
                 listing:
                   summary: Available templates
                   value:
                     templates:
                       - template_id: alberta_title_v1
                         version: 1.1.0
                         page:
                           width: 612
                           height: 792
                           margins: {l: 36, r: 36, t: 48, b: 48}
                         modified_at: "2024-01-01T00:00:00Z"
